{% set name = "spleaf" %}
{% set version = "2.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spleaf-{{ version }}.tar.gz
  sha256: c725b6d422f5f5e138918c280735ad4d94617a452bcfb0669c7a5c5fd6a0e9e1

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - wheel
    - numpy
    - pip
  run:
    - numpy >=1.16
    - scipy >=1.3
    - python

test:
  imports:
    - spleaf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/delisle/spleaf
  summary: Symmetric S+LEAF matrix.
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
