{% set name = "spleaf" %}
{% set version = "2.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spleaf-{{ version }}.tar.gz
  sha256: 51be0f91302b84380b51ea0decf8b946ac8a273bf09c2ef6b22bdded1d7d6fa5

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - numpy >=1.16
    - scipy >=1.3
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - spleaf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/jean-baptiste.delisle/spleaf
  summary: Symmetric S+LEAF matrix.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jbdelisle
